package app.prachang.dummy_data.instagram

import app.prachang.dummy_data.*
import java.util.*

val profileData = Profile(
    userId = UUID.randomUUID().toString(),
    name = "Prachan Ghale",
    username = "g_prachan",
    image = image1,
    followerCount = 233,
    followingCount = 325,
    description = null,
    link = null
)

val myPosts = listOf(
    Post(
        postId = UUID.randomUUID().toString(),
        username = "gprachan",
        userImage = "",
        date = "2 days",
        postImage = listOf(image1, image2),
        likes = 12,
        lastLikeBy = emptyList(),
        description = "",
        commentCount = 12,
    ),
    Post(
        postId = UUID.randomUUID().toString(),
        username = "gprachan",
        userImage = "",
        date = "7 days",
        postImage = listOf(image2, image3, image4, image5),
        likes = 12,
        lastLikeBy = emptyList(),
        description = "",
        commentCount = 12,
    ),
    Post(
        postId = UUID.randomUUID().toString(),
        username = "gprachan",
        userImage = "",
        date = "7 hour",
        postImage = listOf(image3),
        likes = 12,
        lastLikeBy = emptyList(),
        description = "",
        commentCount = 12,
    ),
    Post(
        postId = UUID.randomUUID().toString(),
        username = "gprachan",
        userImage = "",
        date = "1 hour",
        postImage = listOf(image4),
        likes = 12,
        lastLikeBy = emptyList(),
        description = "",
        commentCount = 12,
    ),
    Post(
        postId = UUID.randomUUID().toString(),
        username = "gprachan",
        userImage = "",
        date = "1 Feb",
        postImage = listOf(image5),
        likes = 12,
        lastLikeBy = emptyList(),
        description = "",
        commentCount = 12,
    ),
    Post(
        postId = UUID.randomUUID().toString(),
        username = "gprachan",
        userImage = "",
        date = "1 day",
        postImage = listOf(image6),
        likes = 12,
        lastLikeBy = emptyList(),
        description = "",
        commentCount = 12,
    ),
    Post(
        postId = UUID.randomUUID().toString(),
        username = "gprachan",
        userImage = "",
        date = "1 mins ago",
        postImage = listOf(image7),
        likes = 12,
        lastLikeBy = emptyList(),
        description = "",
        commentCount = 12,
    ),
    Post(
        postId = UUID.randomUUID().toString(),
        username = "gprachan",
        userImage = "",
        date = "1 day",
        postImage = listOf(image8),
        likes = 12,
        lastLikeBy = emptyList(),
        description = "",
        commentCount = 12,
    ),
    Post(
        postId = UUID.randomUUID().toString(),
        username = "gprachan",
        userImage = "",
        date = "1 mins ago",
        postImage = listOf(image9),
        likes = 12,
        lastLikeBy = emptyList(),
        description = "",
        commentCount = 12,
    ),
    Post(
        postId = UUID.randomUUID().toString(),
        username = "gprachan",
        userImage = "",
        date = "2 days",
        postImage = listOf(image10, image2),
        likes = 12,
        lastLikeBy = emptyList(),
        description = "",
        commentCount = 12,
    ),
    Post(
        postId = UUID.randomUUID().toString(),
        username = "gprachan",
        userImage = "",
        date = "7 days",
        postImage = listOf(image11, image3, image4, image5),
        likes = 12,
        lastLikeBy = emptyList(),
        description = "",
        commentCount = 12,
    ),
    Post(
        postId = UUID.randomUUID().toString(),
        username = "gprachan",
        userImage = "",
        date = "7 hour",
        postImage = listOf(image12),
        likes = 12,
        lastLikeBy = emptyList(),
        description = "",
        commentCount = 12,
    ),
    Post(
        postId = UUID.randomUUID().toString(),
        username = "gprachan",
        userImage = "",
        date = "1 hour",
        postImage = listOf(image13),
        likes = 12,
        lastLikeBy = emptyList(),
        description = "",
        commentCount = 12,
    ),
    Post(
        postId = UUID.randomUUID().toString(),
        username = "gprachan",
        userImage = "",
        date = "1 Feb",
        postImage = listOf(image14),
        likes = 12,
        lastLikeBy = emptyList(),
        description = "",
        commentCount = 12,
    ),
    Post(
        postId = UUID.randomUUID().toString(),
        username = "gprachan",
        userImage = "",
        date = "1 day",
        postImage = listOf(image15),
        likes = 12,
        lastLikeBy = emptyList(),
        description = "",
        commentCount = 12,
    ),
    Post(
        postId = UUID.randomUUID().toString(),
        username = "gprachan",
        userImage = "",
        date = "1 mins ago",
        postImage = listOf(image16),
        likes = 12,
        lastLikeBy = emptyList(),
        description = "",
        commentCount = 12,
    ),
    Post(
        postId = UUID.randomUUID().toString(),
        username = "gprachan",
        userImage = "",
        date = "1 day",
        postImage = listOf(image17),
        likes = 12,
        lastLikeBy = emptyList(),
        description = "",
        commentCount = 12,
    ),
    Post(
        postId = UUID.randomUUID().toString(),
        username = "gprachan",
        userImage = "",
        date = "1 mins ago",
        postImage = listOf(image18),
        likes = 12,
        lastLikeBy = emptyList(),
        description = "",
        commentCount = 12,
    ),
    Post(
        postId = UUID.randomUUID().toString(),
        username = "gprachan",
        userImage = "",
        date = "2 days",
        postImage = listOf(image19, image2),
        likes = 12,
        lastLikeBy = emptyList(),
        description = "",
        commentCount = 12,
    ),
    Post(
        postId = UUID.randomUUID().toString(),
        username = "gprachan",
        userImage = "",
        date = "7 days",
        postImage = listOf(image20, image3, image4, image5),
        likes = 12,
        lastLikeBy = emptyList(),
        description = "",
        commentCount = 12,
    ),
    Post(
        postId = UUID.randomUUID().toString(),
        username = "gprachan",
        userImage = "",
        date = "1 mins ago",
        postImage = listOf(image16),
        likes = 12,
        lastLikeBy = emptyList(),
        description = "",
        commentCount = 12,
    ),
)